// This file is automatically generated. Do not edit it directly.
import { createBrowserClient } from '@supabase/ssr';
import { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export const createSupabaseClient = () => {
  if (!SUPABASE_URL) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL');
  }
  if (!SUPABASE_ANON_KEY) {
    throw new Error('Missing NEXT_PUBLIC_SUPABASE_ANON_KEY');
  }

  return createBrowserClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
};

let client: ReturnType<typeof createSupabaseClient> | undefined;

export const getSupabaseClient = () => {
  if (client) {
    return client;
  }

  client = createSupabaseClient();

  return client;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
